- name: Install catalogue Component package
  hosts: catalogue
  become: yes
  tasks:
  - name: setup NPM source
    ansible.builtin.script: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
  

